### ISSUE TITLE
Cannot assemble an assembly file (.mjil) into a binary script (.mjo) in Vietnamese

### ISSUE THREAD

**Issue by TranDatk** [AtomCrafty/MajiroTools#8]
1. After using the command
`maji disassemble sta000_prologue.mjo`

2. It will create 2 files:
- sta000_prologue.mjres
- sta000_prologue.mjil

After I changed the file sta000_prologue.mjres with the following content:
L1,"It's a warm afternoon, about a week into my summer break. Try it"

3. Then I used the command
`maji assemble sta000_prologue.mjil`

4. It reported an error:
```
Command assemble failed with an error:
Unable to translate Unicode character \\u1EED at index 60 to specified code page.
at EncoderExceptionFallbackBuffer.Fallback
at EncoderFallbackBufferHelper.InternalFallback
at DBCSCodePageEncoding.GetByteCount
at EncodingNLS.GetByteCount
at Assembler.GetInstructionSize in Assembler.cs:790
at ControlFlowPass.ToInstructionList in ControlFlowPass.cs:242
at MjoScript.ToInstructionList in MjoScript.cs:187
at Assembler.AssembleScript in Assembler.cs:657
at AssembleCommand.Execute in AssembleCommand.cs:50
at CommandManager.TryRun in CommandManager.cs:33
```

How can I get it to convert Vietnamese characters, maybe utf-16

![image](https://github.com/user-attachments/assets/249c6b8e-8416-403a-a1d9-a9a1f1f27924)

**Comment by AtomCrafty** [comment]
Strings within mjo scripts are [Shift-JIS](https://en.wikipedia.org/wiki/Shift_JIS) encoded, so they can only contain a limited set of characters. Your best bet is to map every Vietnamese character to a Japanese one and use something like [UIF](https://github.com/AtomCrafty/UniversalInjectorFramework) to replace them at runtime.

**Comment by TranDatk** [comment]
Thanks for replying, I have read the UIF library, it is really impressive, but I am a little confused about how to use it, please help me.

I have built your project, and it created for me a folder x64\d3d11
in this folder there are 4 files and 1 folder as follows:

+ d3d11.pdb
+ d3d11.lib
+ d3d11.exp
+ d3d11.dll
And the object folder

What I need to do now is to take the d3d11.dll file and put it in the game's executable folder and create a config.json file with the features I want, here is to replace characters.

If I did it right, I wonder why there are no proxy.dlls available for users to just copy and create a config.json file?

**Comment by AtomCrafty** [comment]
You got the right idea, but there are a few steps missing.

- First, you'll have to decide which proxy dll to use. It has to be a dll that the target executable depends on, otherwise it won't be loaded at all. To check which dlls are imported by your exe, you can use [this tool](https://github.com/lucasg/Dependencies/releases/tag/v1.11.1), or you can send me the game executable and I can check for you.
- Secondly, when building with Visual Studio, select the appropriate proxy from the configuration list at the top.
![image](https://github.com/user-attachments/assets/75a95519-0161-44a3-997b-4fcda311ad39)
I don't provide precompiled proxy dlls since UIF is generally meant for people with some experience with code injection, so they should be able to compile the project themself. And the number of supported proxies is fairly large by now, so it would be annoying to build all of them every time I change something.
- Building that configuration will produce a dll file with the name of the proxy you selected. This needs to be placed in the game directory so the custom dll shadows the one provided by Windows.
- Finally, a file called `uif_config.json` needs to be present in the same directory as the dll. The readme file from the UIF repository isn't quite up to date, so it still shows an old name. I'll need to take some time to update the description of the config file format, but for you something like this should work:

```json
{
    "injector": {
        "enable": true
    },
    "allocate_console": true,
    "text_processor": {
        "enable": true,
        "debug": false,
        "rules": [
            {
                "type": "replace_chars",
                "source_chars": "ｱｲｳｴｵ",
                "target_chars": "áíúéó"
            }
        ]
    }
}
```

**Comment by TranDatk** [comment]
Sorry for the late reply, I used to check the game dependencies with the tool you sent, it has a lot of dependencies, and only 2 of them I saw you mentioned in the document:

+ d3d9.dll
+ d3d11.dll

I understand the following steps you guided me, but does the game have so many dll files, do I have to create all of those proxy.dlls myself if they are not available? Or are there only special dlls that need to be overwritten?

![image](https://github.com/user-attachments/assets/7cbe49d6-40f5-41c9-a66c-7ccbccfcc540)

**Comment by AtomCrafty** [comment]
If the game loads d3d9.dll and d3d11.dll, just use one of those proxies. Creating a new proxy is only necessary if the target executable does not import any of the proxies included with UIF.

**Comment by TranDatk** [comment]
Wow that's impressive, I had a lot of trouble when many visual novels don't support utf-16 for Vietnamese, your way will be extremely effective, thank you for creating it 🤩

**Comment by TranDatk** [comment]
Sorry for bothering you again, the other day I just tried the characters as you instructed, but when I added some other words, it didn't work, because in Vietnamese there are many accents with vowel words, for example: "à ả ã ạ ư ứ ừ ự ô ố ồ ộ ư ứ ừ ự" and many more, you can see I replaced it with the word あ -> ừ as in the picture will be turned into a square character, thank you for your time!

This is uif_config.json:
```json
{
    "injector": {
        "enable": true
    },
    "allocate_console": true,
    "text_processor": {
        "enable": true,
        "debug": false,
        "rules": [
            {
                "type": "replace_chars",
                "source_chars": "ｱｲｳｴｵあ",
    		"target_chars": "áíúéóừ"
            }
        ]
    }
}
```

![image](https://github.com/user-attachments/assets/bbdadf7a-0d04-4330-b48b-69f09b81f9cf)

**Comment by AtomCrafty** [comment]
This is almost certainly unrelated to UIF or MajiroTools. The font used by the game probably simply doesn't contain these characters. You can use UIF's [Font Manager](https://github.com/AtomCrafty/UniversalInjectorFramework?tab=readme-ov-file#font-manager) feature to force the game to use a different font.

**Comment by TranDatk** [comment]
Wow, it works really well, thank you very much, there is only one small problem, if you look closely, the character after being replaced leaves a space quite far from the rest, any ideas?
![image](https://github.com/user-attachments/assets/e4c958f4-36de-44cc-a200-59bb912279f9)

![image](https://github.com/user-attachments/assets/a767de2b-dd6c-40f3-ad36-8b3a0a6dca21)

**Comment by AtomCrafty** [comment]
Shift-JIS is a double-byte character set, which means that some characters (like A and ｱ) only need one byte to be encoded while others (like あ and all kanji) need two bytes. Characters using a single byte are known as half-width and those using two bytes as full-width characters.

The game will use the source character of your mapping for text layout, so your issue is that you're using the full-width character あ as the source character for ừ. Use one of the half-width characters in [this table](https://en.wikipedia.org/wiki/Half-width_kana#Half-width_table) instead and the spacing should be fixed.

**Comment by TranDatk** [comment]
I got the idea, thank you very much, I will post an article introducing this repo to Vietnamese translators!!!
